version: '3'
services:
    monitor-service:
        build: .
        ports:
        - "8080:8080"
        environment: 
            MYSQL_HOST: db
            REDIS_HOST: redis
        depends_on:
        - db
        - redis
        restart: always

    redis:
        image: "redis:alpine"
        restart: always

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: monitor_service

    web:
        build: 
            context: ./webapp
            args:
                REACT_APP_SERVICE_HOST: ${MONITOR_HOST:-localhost} 
                REACT_APP_SERVICE_PORT: 8080
                REACT_APP_MINIO_HOST: ${MINIO_HOST:-localhost}
                REACT_APP_MINIO_PORT: 9000
                REACT_APP_MINIO_ACCESS_KEY: minio
                REACT_APP_MINIO_SECRET_KEY: minio123
        ports: 
        - "${WEB_PORT:-80}:80"
        depends_on:
        - monitor-service
        restart: always
    
    minio1:
        image: minio/minio:RELEASE.2020-04-10T03-34-42Z
        volumes:
            - data1-1:/data1
            - data1-2:/data2
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server http://minio{1...2}/data{1...2}
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
    minio2:
        image: minio/minio:RELEASE.2020-04-10T03-34-42Z
        volumes:
            - data2-1:/data1
            - data2-2:/data2
        ports:
            - "9002:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server http://minio{1...2}/data{1...2}
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
    minio-init:
        build: ./minio-init
        depends_on:
            - minio1
        restart: on-failure
        environment:
            MINIO_HOST: minio1
            MINIO_PORT: 9000
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
volumes:
    mysql-data:
    data1-1:
    data1-2:
    data2-1:
    data2-2:
