version: '3'
services:
    monitor-service:
        build: .
        # ports:
        # - "8088:8088"
        environment: 
            MYSQL_HOST: 127.0.0.1
            REDIS_HOST: 127.0.0.1
            VIDEO_TR_HOST: 127.0.0.1
            DEPLOY_CODE: 150526B0012000310068
            KAFKA_SERVER: 49.4.53.185:7072
        network_mode: host
        depends_on:
        - db
        - redis
        restart: always

    redis:
        image: "redis:alpine"
        restart: always
        ports:
        - "6379:6379"

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        - "3306:3306"
        volumes: 
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: monitor_service

    web:
        build: 
            context: ./webapp
            args:
                # REACT_APP_SERVICE_HOST: 222.74.238.102
                # REACT_APP_SERVICE_PORT: 8088
                # REACT_APP_MINIO_HOST: 222.74.238.102
                # REACT_APP_MINIO_PORT: 9000
                REACT_APP_SERVICE_PORT: 8088
                REACT_APP_REMOTE_SERVICE_PORT: 8089
                REACT_APP_LOCAL_VIDEO_PORT: 8090
                REACT_APP_REMOTE_VIDEO_PORT: 8091
                REACT_APP_MINIO_ACCESS_KEY: minio
                REACT_APP_MINIO_SECRET_KEY: minio123
        ports: 
        - "${WEB_PORT:-80}:80"
        depends_on:
        - monitor-service
        restart: always
    
    minio1:
        image: minio/minio:RELEASE.2020-04-10T03-34-42Z
        volumes:
            - data1-1:/data1
            - data1-2:/data2
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server http://minio{1...2}/data{1...2}
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
    minio2:
        image: minio/minio:RELEASE.2020-04-10T03-34-42Z
        volumes:
            - data2-1:/data1
            - data2-2:/data2
        ports:
            - "9002:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server http://minio{1...2}/data{1...2}
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
    minio-init:
        build: ./minio-init
        depends_on:
            - minio1
        restart: on-failure
        environment:
            MINIO_HOST: minio1
            MINIO_PORT: 9000
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
volumes:
    mysql-data:
    data1-1:
    data1-2:
    data2-1:
    data2-2:
